services:

  backend:
    image: node:18-alpine
    container_name: backend_node
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
      - ./data:/usr/src/app/data
    command: sh -c "npm install && npm run dev" # dev com nodemon
    ports:
      - "3001:3001"
    restart: always
  # frontend:
  #   image: node:18-alpine
  #   container_name: frontend_node
  #   working_dir: /usr/src/app
  #   volumes:
  #     - ./frontend:/usr/src/app
  #   command: sh -c "npm install && npm start" # react-scripts start
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backen