services:
  backend:
    image: node:18-alpine
    container_name: backend_node
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
      - ./data:/usr/src/app/data
    command: sh -c "npm install && npm run dev" # dev com nodemon
    ports:
      - "3001:3001"
    restart: always
